### ISSUE TITLE
Issue generating deployment template

### ISSUE THREAD

**Issue by rgbrizzlehizzle** [fkorotkov/k8s-kotlin-dsl#27]
Hi,

I'm having issues generating a valid deployment, hopefully this is just an easy error in my DSL.  In trying to follow the [kubernetes docs](https://kubernetes.io/docs/concepts/workloads/controllers/deployment) for deployments, I thought it would be a good "hello world" to try to recreate this deployment with Kotlin

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

My attempt thus far has lead me to the following DSL

```
class SimpleDeployment : Deployment() {
  init {
    metadata {
      name = "nginx-deployment"
      labels = mapOf("app" to "nginx")
    }
    spec {
      replicas = 3
      selector {
        matchLabels = mapOf(
          "app" to "nginx"
        )
      }
      template {
        metadata {
          labels = mapOf("app" to "nginx")
        }
        spec {
          newContainer {
            name = "nginx"
            image = "nginx:1.14.2"
            ports = listOf(newContainerPort { containerPort = 80 })
          }
        }
      }
    }
  }
}
```

Unfortunately, this code block seems to sorta fizzle out at the template block, because the resulting YAML is 

```
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "nginx"
  name: "nginx-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx"
  template: {}
```

I'm pretty new to Kotlin and in all honest am kind of struggling to debug it 😕 

Currently I am using the following versions 

```
  val kFabric8Version = "2.8"
  val fabric8Version = "4.10.3"
  ... 
  implementation("com.fkorotkov:kubernetes-dsl:$kFabric8Version")
  implementation("io.fabric8:kubernetes-client:$fabric8Version")
```

Any tips/advice would be amazing!
